./src/test/run-pass/destructor-ordering.rs:25:0:25:2: [1;31merror:[0m expected item but found io
./src/test/run-pass/destructor-ordering.rs:25 io fn check_order(port[order_info] expected_p) {
                                              ^~
rt: ---
rt: 17b9:main:main:                   upcall fail 'explicit failure', src/comp/syntax/parse/parser.rs:112
rt: 17b9:main:                        domain main @0x96d304c root task failed
