error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:23:9
   |
LL |         Err(err)?;
   |         ^^^^^^^^^ help: try: `return Err(err)`
   |
note: the lint level is defined here
  --> $DIR/try_err.rs:4:9
   |
LL | #![deny(clippy::try_err)]
   |         ^^^^^^^^^^^^^^^

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:33:9
   |
LL |         Err(err)?;
   |         ^^^^^^^^^ help: try: `return Err(err.into())`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:53:17
   |
LL |                 Err(err)?;
   |                 ^^^^^^^^^ help: try: `return Err(err)`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:72:17
   |
LL |                 Err(err)?;
   |                 ^^^^^^^^^ help: try: `return Err(err.into())`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:92:23
   |
LL |             Err(_) => Err(1)?,
   |                       ^^^^^^^ help: try: `return Err(1)`
   |
   = note: this error originates in the macro `__inline_mac_fn_calling_macro` (in Nightly builds, run with -Z macro-backtrace for more info)

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:99:23
   |
LL |             Err(_) => Err(inline!(1))?,
   |                       ^^^^^^^^^^^^^^^^ help: try: `return Err(inline!(1))`
   |
   = note: this error originates in the macro `__inline_mac_fn_calling_macro` (in Nightly builds, run with -Z macro-backtrace for more info)

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:126:9
   |
LL |         Err(inline!(inline!(String::from("aasdfasdfasdfa"))))?;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `return Err(inline!(inline!(String::from("aasdfasdfasdfa"))))`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:133:9
   |
LL |         Err(io::ErrorKind::WriteZero)?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `return Poll::Ready(Err(io::ErrorKind::WriteZero.into()))`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:135:9
   |
LL |         Err(io::Error::new(io::ErrorKind::InvalidInput, "error"))?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `return Poll::Ready(Err(io::Error::new(io::ErrorKind::InvalidInput, "error")))`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:143:9
   |
LL |         Err(io::ErrorKind::NotFound)?
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `return Poll::Ready(Some(Err(io::ErrorKind::NotFound.into())))`

error: returning an `Err(_)` with the `?` operator
  --> $DIR/try_err.rs:152:16
   |
LL |         return Err(42)?;
   |                ^^^^^^^^ help: try: `Err(42)`

error: aborting due to 11 previous errors

